version: 2
updates:
    # NPM dependencies
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'monday'
          time: '09:00'
      allow:
          - dependency-type: 'direct'
          - dependency-type: 'indirect'
      pull-request-branch-name:
          separator: '/'
      commit-message:
          prefix: 'chore(deps)'
          include: 'scope'
      reviewers:
          - 'sandovaldavid'
      assignees:
          - 'sandovaldavid'
      open-pull-requests-limit: 5
      rebase-strategy: 'auto'
      groups:
          critical-dependencies:
              dependency-types:
                  - 'direct'
              update-types:
                  - 'major'
          security-updates:
              patterns:
                  - 'security*'
          dev-dependencies:
              dependency-types:
                  - 'direct'
                  - 'indirect'
              dependency-groups:
                  - 'dev-dependencies'

    # GitHub Actions
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'monday'
          time: '10:00'
      pull-request-branch-name:
          separator: '/'
      commit-message:
          prefix: 'ci(actions)'
          include: 'scope'
      reviewers:
          - 'sandovaldavid'
